# Docker-compose.yml file for prd/readers project

# Nginx
nginx:
    build: ./nginx
    volumes:
        - .:/usr/src/app
    links:
        - django:django

    ports:
        - "80:80"

# This defines a service for the Django app
django:
    build: .
    volumes:
        - .:/usr/src/app
    expose:
        - "8000"
    links:
        - postgres:postgres
        - redis:redis

# REDIS
redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"


# This defines a service for the Postgres database
postgres:
    image: postgres:9.3
